/*
Copyright 2017 Nils Deppe
Distributed under the Boost Software License.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*
 * Compile the code using:
 * clang++ -std=c++1z ./variadic-using.cpp
 */

#include <iostream>
#include <type_traits>

template <class... Lambdas>
struct overload : Lambdas... {
  explicit overload(Lambdas... lambdas) : Lambdas(std::move(lambdas))... {}

  using Lambdas::operator()...;
};

template <class... Lambdas>
overload<Lambdas...> make_overload(Lambdas... lambdas) {
  return overload<Lambdas...>(std::move(lambdas)...);
}

struct my_type1 {
  int func(int a) { return 2 * a; }
};

struct my_type2 {};

template <class T, class = std::void_t<>>
struct has_func : std::false_type {};

template <class T>
struct has_func<
    T, std::void_t<decltype(std::declval<T>().func(std::declval<int>()))>>
    : std::true_type {};

static_assert(has_func<my_type1>::value, "");
static_assert(not has_func<my_type2>::value, "");

template <class T>
void func(T t) {
  auto my_lambdas = make_overload(
      [](auto& f, std::integral_constant<bool, true>) {
        std::cout << "True " << f.func(2) << "\n";
      },
      [](auto& f, std::integral_constant<bool, false>) {
        std::cout << "False\n";
      });
  my_lambdas(t, std::integral_constant<bool, has_func<T>::value>{});
}

int main() {
  auto my_lambdas = make_overload(
      [](std::integral_constant<bool, true>) { std::cout << "True\n"; },
      [](std::integral_constant<bool, false>) { std::cout << "False\n"; });
  my_lambdas(std::integral_constant<bool, true>{});
  my_lambdas(std::integral_constant<bool, false>{});

  func(my_type1{});
  func(my_type2{});
}
